### ISSUE TITLE
Icons don't show up in Tasks list

### ISSUE THREAD

**Issue by MitekDev-Mcalvin** [jabbera/my-vsts-tasks#1]
I have installed your extension to my VSTS instance and I am not seeing the tasks that you defined. 
![tasksmissing](https://cloud.githubusercontent.com/assets/11964440/16248971/a2816b16-37c7-11e6-9b57-8a527d302b54.png)

**Comment by jabbera** [comment]
I've never used this on a vsts service. Are you using an on perm agent or a hosted agent?

**Comment by MitekDev-Mcalvin** [comment]
Its an On-Prem agent but I think the tasks are separate from the agents (it should show up for both)

**Comment by jabbera** [comment]
Agreed. I'm just asking so I can setup an accurate reproduction.

**Comment by jabbera** [comment]
I've tested this every which way from Sunday and I can't seem to reproduce your issue. Can you trying uninstalling\then re-installing the extension?

Thanks!

**Comment by MitekDev-Mcalvin** [comment]
After uninstalling and reinstalling, I do see the tasks in the task list. Maybe its a VSTS problem.

Thanks.
