### ISSUE TITLE
Install with and without custom user.

### ISSUE THREAD

**Issue by tortocan** [jabbera/my-vsts-tasks#11]
When you try to install the service as other that custom user be sure to clear the username field and password field, as they will get pushed to the console as a command even if you chose Local Service instead.

**Comment by jabbera** [comment]
Thanks for catching this. I've committed a fix and will push an update sometime in the future.

**Comment by tortocan** [comment]
Great news, fast response !
Thanks.

**Comment by jabbera** [comment]
This has been published as version: 3.1774.0
