### ISSUE TITLE
FileNotFoundException

### ISSUE THREAD

**Issue by seilorjunior** [jabbera/my-vsts-tasks#12]
Hi i am getting this error to install.

4/11/2017 9:25:11 AM - Microsoft VSIX Installer
4/11/2017 9:25:11 AM - -------------------------------------------
4/11/2017 9:25:11 AM - vsixinstaller.exe version:
4/11/2017 9:25:11 AM - 15.0.26403.3 built by: D15SVC
4/11/2017 9:25:11 AM - -------------------------------------------
4/11/2017 9:25:11 AM - Command line parameters:
4/11/2017 9:25:11 AM - C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\VSIXInstaller.exe,C:\Users\a031160\Downloads\jabbera.windows-service-release-tasks-3.1774.0.vsix
4/11/2017 9:25:11 AM - -------------------------------------------
4/11/2017 9:25:11 AM - Microsoft VSIX Installer
4/11/2017 9:25:11 AM - -------------------------------------------
4/11/2017 9:25:11 AM - Failed to initialize settings for Isolated Shell C:\Program Files (x86)\Microsoft SQL Server\130\Tools\Binn\ManagementStudio\ssms.exe: Unable to find an entry point named '?' in DLL 'PkgdefMgmt.dll'.
4/11/2017 9:25:11 AM - Failed to initialize settings for Isolated Shell C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\ManagementStudio\ssms.exe: Unable to find an entry point named '?' in DLL 'PkgdefMgmt.dll'.
4/11/2017 9:25:11 AM - Initializing Install...
4/11/2017 9:25:11 AM - Extension Details...
4/11/2017 9:25:11 AM - 	Identifier         : windows-service-release-tasks
4/11/2017 9:25:11 AM - 	Name               : Windows Service Release Tasks
4/11/2017 9:25:11 AM - 	Author             : jabbera
4/11/2017 9:25:11 AM - 	Version            : 3.1774.0
4/11/2017 9:25:11 AM - 	Description        : Release management tasks for the starting, stopping, and install(TopShelf) of windows services.
4/11/2017 9:25:11 AM - 	Locale             : en-US
4/11/2017 9:25:11 AM - 	MoreInfoURL        : 
4/11/2017 9:25:11 AM - 	InstalledByMSI     : False
4/11/2017 9:25:11 AM - 	SupportedFrameworkVersionRange : [0.0,2147483647.2147483647]
4/11/2017 9:25:11 AM - 
4/11/2017 9:25:11 AM - 	SignatureState     : Unsigned
4/11/2017 9:25:11 AM - 	Supported Products : 
4/11/2017 9:25:11 AM - 		Microsoft.VisualStudio.Services
4/11/2017 9:25:11 AM - 			Version : 
4/11/2017 9:25:11 AM - 
4/11/2017 9:25:11 AM - 	References         : 
4/11/2017 9:25:11 AM - Signature Details...
4/11/2017 9:25:11 AM - 	Extension is not signed.
4/11/2017 9:25:11 AM - 
4/11/2017 9:25:11 AM - Searching for applicable products...
4/11/2017 9:25:11 AM - Found installed product - Microsoft Visual Studio 2013 Shell (Integrated)
4/11/2017 9:25:11 AM - Found installed product - Microsoft Visual Studio Enterprise 2015
4/11/2017 9:25:11 AM - Found installed product - Microsoft Visual Studio Professional 2015
4/11/2017 9:25:11 AM - Found installed product - Microsoft Visual Studio Community 2015
4/11/2017 9:25:11 AM - Found installed product - Microsoft Visual Studio 2015 Shell (Integrated)
4/11/2017 9:25:11 AM - Found installed product - Global Location
4/11/2017 9:25:11 AM - Found installed product - Visual Studio Enterprise 2017
4/11/2017 9:25:11 AM - Found installed product - Visual Studio Community 2017 (2)
4/11/2017 9:25:11 AM - System.IO.FileNotFoundException: C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\devenv.exe
   at System.Diagnostics.FileVersionInfo.GetVersionInfo(String fileName)
   at VSIXInstaller.SupportedVSSKU.get_VersionWithBuildRevisionInfo()
   at VSIXInstaller.App.IsValidSKUForExtension(SupportedVSSKU supportedSKU, IExtension extension, List`1 validSKUs)
   at VSIXInstaller.App.ShouldAddSkuToValidSkuList(SupportedVSSKU sku, IInstallableExtension extension, List`1 validSKUs)
   at VSIXInstaller.App.GetInstallableData(String vsixPath, Boolean isRepairSupported, IEnumerable`1& skuData)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

**Comment by jabbera** [comment]
Please provide more details. Reproduction steps? What version are you attempting to install this on? OnPrem? Patch Level?

**Comment by seilorjunior** [comment]
I am only getting this error to install the vsix file. both on my machine and on our test env

**Comment by jabbera** [comment]
This can't be installed in visual studio.
