### ISSUE TITLE
Spaces not supported in service display name and service description

### ISSUE THREAD

**Issue by mikanyg** [jabbera/my-vsts-tasks#13]
I get the following error when setting service display name and service description using the topshelf installer task to strings containing characters and spaces.

_Topshelf.HostFactory Error: 0 : An exception occurred creating the host, Topshelf.HostConfigurationException: The service was not properly configured:_ 

The task itself did not fail, but adding system.debug variable showed why service could not be found on target machine.

Even tried wrapping in single and double quotes with same result.

**Comment by ferarias** [comment]
I have created a pull request to solve this.
