### ISSUE TITLE
Request to Provided Uninstall Service Task

### ISSUE THREAD

**Issue by sanjaymunjal** [jabbera/my-vsts-tasks#18]
Hi, 
Wondering if you can add Uninstall Service Task. We are trying to use the task in our CI pipeline. During changes we need to the following: Stop Service, Uninstall Service, Replace the Destination Folder with updated Binaries, Install the Service with updated binaries and Start the service. 

Current install service task does provide uninstall option but we want to replace the binaries before we install it. Any alternate suggestion will be welcome.

Thanks in advance. 

Regards,
Sanjay

**Comment by jabbera** [comment]
Can I ask why? The workflow we have established here is to use the stop task, but at the same time set the startup type to disabled in case of deployment failure.

**Comment by sanjaymunjal** [comment]
How one can replace the binaries which are being changed as part of the CI/CD Pipeline for a installed windows service? My understanding is that we need to uninstall before we can replace the service binaries and then install it again. For e.g. Service related dlls may changed and during deployment we want to update these. Sorry in case I am missing something here in relation to windows service installation. Thanks in advance.

**Comment by jabbera** [comment]
You should not need to uninstall to replace binaries. You do need to stop the service however. As I said, we do a stop, copy, re-install (the install task with uninstall checked) and a start for over 100 deployments. Works great.

**Comment by sanjaymunjal** [comment]
Thanks for you reply. That worked. I misunderstood that in order to update the service, we have to uninstall it. You can close this issue. 
Thanks a lot.

**Comment by jabbera** [comment]
Glad I could help!
