### ISSUE TITLE
##[error]Microsoft.PowerShell.Commands.WriteErrorException: Method invocation failed because [System.String[]] doesn't contain a method named 'Trim'. 

### ISSUE THREAD

**Issue by tomhundley** [jabbera/my-vsts-tasks#2]
## [error]Microsoft.PowerShell.Commands.WriteErrorException: Method invocation failed because [System.String[]] doesn't contain a method named 'Trim'.

Thoughts on this?

My build server is running Server 2012 R2
Thanks!

**Comment by jabbera** [comment]
Which task are you using?

**Comment by jabbera** [comment]
Someone else reported this internally. This requires powershell 5

**Comment by dibble-james** [comment]
I'm also seeing this error.  Both machines are running Powershell 4 which I am unable to upgrade for various reasons.  Are you likely to make the changes to support this environment?
