### ISSUE TITLE
Feature Request: Support delayed startup type in InstallTopshelfService

### ISSUE THREAD

**Issue by mikanyg** [jabbera/my-vsts-tasks#21]
The --delayed startup type is missing from the list of startup types in InstallTopshelfService

Currently our services are configured in code using this startup type, but the InstallTopshelfService task overrides this, and we are unable to set it in the task.

Please add the --delayed option to the list of startup types.

**Comment by jabbera** [comment]
This is available in the beta: https://github.com/jabbera/my-vsts-tasks/releases/tag/6.189.1

**Comment by jabbera** [comment]
Hi,

any chance you could give this a test before I release it?

**Comment by mikanyg** [comment]
I would like to, but it could be a couple of weeks before I get the time.
