### ISSUE TITLE
deploymentgroups

### ISSUE THREAD

**Issue by ovebastiansen** [jabbera/my-vsts-tasks#26]
Hi,
I found your deploymentgroups branch, and was when you think this will published in the gallery? I am just about to start releasing topshelf services in deploymentgroups, so very keen on trying your extension out.

**Comment by jabbera** [comment]
Are you using vsts or TFS? I don’t have an exact date yet.

Long story: I’ve run out of free build minutes this month and out of principal I refuse to pay for my own. The only thing I use my vsts account for is building and testing these extensions. It seems silly to force me to pay to make Microsoft’s ecosystem better.

**Comment by ovebastiansen** [comment]
Right now this is for a tfs project.

//Ove

On my phone
________________________________

**Comment by jabbera** [comment]
Sorry for the delay. I've really had a hell of a time getting this going. I can upload a visx that you can test with if you are interested.

**Comment by jabbera** [comment]
https://github.com/jabbera/my-vsts-tasks/releases/tag/7.0.0

**Comment by ovebastiansen** [comment]
Cant you create a private agent on your machine? Then you dont have to pay build minutes, you get one free private pipeline pr vsts account.

I will have a look at the new extension to see how it behaves, and report any problems. Are there any known issues with it?

**Comment by jabbera** [comment]
I though it was still 15 bucks a month as my MSDN benefit is associated with my work account, and it’s more about the principal. My extensions are used by 2k plus accounts and are all free:-)

It doesn’t support passwords with spaces:-/ That’s all I know about.

**Comment by ovebastiansen** [comment]
They removed the 15 bucks a while ago, you get one for free now.

What is the password for? For the installed service running user or deployment?

//Ove

On my phone
________________________________

**Comment by jabbera** [comment]
Installing a topshelf service, the service account password can't currently have a space. It's a silly bug but non trivial to fix. I'm working through it now.

**Comment by jabbera** [comment]
As far as I can tell this is a bug in topshelfs command line parser. I can either support spaces or double quote, but not both. I'm going to stick with double quote.

**Comment by ovebastiansen** [comment]
Right for me that is not a problem so should be fine. Will test the extension over the weekend.

//Ove

On my phone
________________________________

**Comment by douglasquintanilha** [comment]
Hi @jabbera , is there a way to test this last release that supports development groups in VSTS ? I've started developing my own extension for this, but yours is light-years ahead of mine. 

The Marketplace one is on version 4.17297.1 and if I got it right the deployment groups are only available on the 7.0.0 version, right ?

Thanks for the extension by the way! You should provide a way for us to donate :)

**Comment by jabbera** [comment]
I’m probably going to release 7 today now that I’ve worked out the reason for my space issue. (Not that there’s anything I can do about it)

It’s a new major version so there’s no risk to my existing users.

**Comment by jabbera** [comment]
This has been released.
