### ISSUE TITLE
Implement appsettings value change ala iis web app

### ISSUE THREAD

**Issue by ovebastiansen** [jabbera/my-vsts-tasks#27]
Any change you have been looking into doing something like [this](https://docs.microsoft.com/en-us/vsts/build-release/tasks/transforms-variable-substitution#xml-variable-substitution)
Would be very nice to just have all appsettings and connectionstring changed out with release variables

**Comment by jabbera** [comment]
It’s unlikely I’ll implement this. It violates SOLID imo. 

That said we do this in our application today. We use slow cheetah to replace interesting settings with tokens at build time. At relleast are time we use any of the tokenizer tasks to replace those tokens (https://marketplace.visualstudio.com/items?itemName=TotalALM.totalalm-tokenization)
