### ISSUE TITLE
Install Topshelf Service - Allow Service Passwords to be marked as Secret

### ISSUE THREAD

**Issue by cjoergensen** [jabbera/my-vsts-tasks#30]
I would be great if the 'Service Password' could handle a variable marked as Secret.

**Comment by cjoergensen** [comment]
There is chance that this would also fix this: #23

**Comment by jabbera** [comment]
Service password works fine with secret variables. There is actually no difference from a task perspective in using a secret or non secret variable.

**Comment by cjoergensen** [comment]
Doh! You're right. Sorry for the inconvenience...

**Comment by jabbera** [comment]
No worries:-)
