### ISSUE TITLE
##[error]Required: 'adminPassword' input

### ISSUE THREAD

**Issue by xlreme** [jabbera/my-vsts-tasks#32]
![image](https://user-images.githubusercontent.com/7971979/39182966-129afb02-47f1-11e8-88ac-7d30db1fa488.png)
![image](https://user-images.githubusercontent.com/7971979/39179539-27478b88-47e7-11e8-8f8f-8dc10d3e02a5.png)
![image](https://user-images.githubusercontent.com/7971979/39179649-5d48bb76-47e7-11e8-8703-152f861e2e57.png)

Hi, any reason for this? i have re-keyed in the admin password as stated in the task but it still giving me the error.

**Comment by jabbera** [comment]
Can you set a variable called system.debug=true and send the entire log for the task? Also check to make sure you don't have any environment specific variables or variable groups overriding the release level variables.

**Comment by xlreme** [comment]
[tasklog_4.log](https://github.com/jabbera/my-vsts-tasks/files/1943323/tasklog_4.log)

Hi Mike, here you go. (FYI, I have manually removed the environment and userID. Both are showing up perfectly on the log)

I have checked the variable, I only have 2 environments sharing the same variable names, which I don't think is the problem. Nothing on my global release variable as well.

The issue happens only my pre-production environment. I have a similar task for my DEV and its working great. The only difference is that the password for the pre-production is secret and I don't know what is it.

**Comment by jabbera** [comment]
The admin password is coming through as empty: INPUT_ADMINPASSWORD (empty)

Can you hard code random text in the field on the task, run again, and upload the log.

I find it difficult to believe I have a mismatched variable name between the task and the power shell given that this is used by 1800 accounts. 

Have you double checked your environment specific variables to be sure there isn’t an override?

**Comment by jabbera** [comment]
Double checked, the variable name matches between the task and the json.

**Comment by xlreme** [comment]
This is strange. I have tested the following:

1) I tried hardcoded the password on the task, it showed up on debug. 
2) Rename the variable name to another name and try again, it doesn't showed on debug
3) Created another variable with old name and with different password, it showed on debug!
3) Tried back the initial variable with the renamed name. It doesn't showed on debug.

I guess is the password issue. I will check the password to see if there is any special char.

**Comment by xlreme** [comment]
Okay, I realized this might be a bug on TFS2015 rather than this task. 

Just to document it here, in case someone else encountered the same issue. 
1) You have a variable that is secret, e.g password
2) You change the variable name
3) The value of the variable shows value but actually, it becomes missing/empty (TFS Bug perhaps)
4) Set the value of the variable to another non-secret value and save
5) Set back the password and secret it. 
6) The task should pick up the value again. 

Thanks Mike. Sorry for any inconvenience caused.

**Comment by jabbera** [comment]
No problem. Thanks for the information!
