### ISSUE TITLE
Required: 'environmentName' input - don't understand what this is

### ISSUE THREAD

**Issue by mmeasor** [jabbera/my-vsts-tasks#35]
I am using this for the first time, and I am stuck getting my Release Definition working because I am getting the error 
    Required: 'environmentName' input

I have a variable named the same way, but that didn't help. I am not sure how to fix this.

Here is how my Install task is set up
![image](https://user-images.githubusercontent.com/4885613/42163143-65256e20-7dcf-11e8-913f-76335abda79b.png)

Here is the actual output of the task running
![image](https://user-images.githubusercontent.com/4885613/42163288-f03343a2-7dcf-11e8-9296-116155d0da5c.png)

**Comment by jabbera** [comment]
Hi,

You need to specify machines you are deploying to (and credentials) at the bottom of your screenshot. If you are using deployment groups, check the box that says deployment group.
Let me know if that solves your issue.

Mike

**Comment by mmeasor** [comment]
Thank you for the quick reply.
That solved the problem, thank you
![image](https://user-images.githubusercontent.com/4885613/42164553-5d92f416-7dd4-11e8-9b19-7c3615a03cbe.png)

**Comment by Thaval** [comment]
This does not seem to work with deployment groups, I'm getting the same error. The fancy thing about this failure is that there is no field to set the environmentName. Where is that coming from?

**Comment by Thaval** [comment]
I found out this happens if the Service is not installed yet. If you check the option "Continue on error", the error message disappears.
