### ISSUE TITLE
Calling Stop service throws the host program or the command type does not support user interaction

### ISSUE THREAD

**Issue by Christoffleroux** [jabbera/my-vsts-tasks#4]
I'm deploying multiple windows services, somtines the stop service step is failing with the following message.

A command that prompts the user failed because the host program or the command type does not support user interaction.

**Comment by jabbera** [comment]
What version are you using?

**Comment by Christoffleroux** [comment]
Using the current team services online version.  I have attached the debug log for the task.
[tasklog_3 (6).zip](https://github.com/jabbera/my-vsts-tasks/files/427348/tasklog_3.6.zip)

**Comment by jabbera** [comment]
It's a bug here: https://github.com/jabbera/my-vsts-tasks/blob/master/Extensions/WindowsServiceReleaseTasks/Src/Tasks/StopWindowsService/StopWindowsServiceIntern.ps1#L42

Write-Host isn't supported remoted. I'll get a new version out.

**Comment by Christoffleroux** [comment]
Thank you

Sent from my Samsung device

-------- Original message --------

**Comment by brunobertechini** [comment]
Was this released to VSTS online servers ?

**Comment by jabbera** [comment]
I'm not familiar with the VSTS upgrade process, but I'm assuming you would need to tell VSTS to upgrade your collection to the current version?
