### ISSUE TITLE
Feature Request: Set Service Recovery Options

### ISSUE THREAD

**Issue by PaulMEdwards** [jabbera/my-vsts-tasks#40]
Our application includes a Windows Service which likes to gobble up RAM and take forever to shut down... So long that it often must be terminated during the deployment.

Our Production servers are configured to automatically restart the service only 1 minute after it "fails" (or is terminated)... This often results in the service coming back up while we're still deploying which subsequently results in files for the service failing to copy because they are in use.

Would it be possible to implement the ability to adjust the Recovery options so that we can change the failure action options and/or restart service after N minutes when stopping and starting the services? I found these posts with detailed info on how to do so:
- https://stackoverflow.com/questions/9267639/set-remote-services-recovery-options-using-powershell
- https://evotec.xyz/set-service-recovery-options-powershell/

**Comment by jabbera** [comment]
Hi Paul,

This is doable, but I’m a bit short on time and I’ve no need for this functionality myself. I’d be happy to accept a PR though.

Mike
