### ISSUE TITLE
Stopping Windows Service log output lacks Service Names

### ISSUE THREAD

**Issue by PaulMEdwards** [jabbera/my-vsts-tasks#41]
I noticed that the log output for the Stop Service command no longer displays the Name(s) of the Service(s) being Stopped...

![image](https://user-images.githubusercontent.com/153847/43420446-89b77960-93f8-11e8-93dd-6aeed8f24f34.png)

It is a simple variable name problem... The variable is initialized as plural:

https://github.com/jabbera/my-vsts-tasks/blob/2d388dd7eb2c14d69073b50239e9b621defdd54b/Extensions/WindowsServiceReleaseTasks/Src/Tasks/StopWindowsService/StopWindowsService.ps1#L7

But the line that prints the message is singular:

https://github.com/jabbera/my-vsts-tasks/blob/2d388dd7eb2c14d69073b50239e9b621defdd54b/Extensions/WindowsServiceReleaseTasks/Src/Tasks/StopWindowsService/StopWindowsService.ps1#L14

I will submit a PR fix shortly...

**Comment by jabbera** [comment]
Thanks. I did a new PR to avoid the merge commit. I'll post a new version this week.
