### ISSUE TITLE
Account credentials should not be required

### ISSUE THREAD

**Issue by robertmclaws** [jabbera/my-vsts-tasks#47]
Hello! We use this tool to deploy our TopShelf services using Azure DevOps Server. We're trying to remove the need for user credentials to be a part of our build process, given that credentials need to rotate every X number of days here. With your tasks, the UI does not mark the AdminLogin and Password fields as required (yay!). HOWEVER, if you omit them, the command fails with the message `[error]Required: 'adminUserName' input` (boo!).

It would be really great if you could update the task to NOT require credentials.

Thanks!

**Comment by jabbera** [comment]
I'm assuming that means you are using the concept of a deployment group from Azure DevOps? You should be able to check that option for the task and it will not attempt to retrieve those credentials:

https://github.com/jabbera/my-vsts-tasks/blob/9d6fcee1d1bd7373741052d5b4a6f4bc62b0efa3/Extensions/WindowsServiceReleaseTasks/Src/Tasks/InstallTopshelfService/InstallTopshelfService.ps1#L82

**Comment by robertmclaws** [comment]
It's not a deployment group. I'm just leveraging a specific Active Directory build user, and giving that user permission to do things. It's still running on a build server that is not the deployment target. So I still need to be connecting to a remote PowerShell session, just without credentials.

**Comment by jabbera** [comment]
The deployment technology isn’t just remoting. It’s an entire “deploymentsdk”. I’m not sure it’s possible. If I have time I’ll look into it, but I’d take a PR.

**Comment by jabbera** [comment]
This is not possible given the Microsoft solution I'm leveraging.
