### ISSUE TITLE
How are you including utility.ps1 in your installer

### ISSUE THREAD

**Issue by crshnbrn66** [jabbera/my-vsts-tasks#5]
When compiling this and adding to TFS how are you adding your utility script in?? Manually?

**Comment by jabbera** [comment]
It's in the gulpfile.js. See calls to copy common modules.

**Comment by jabbera** [comment]
It's in the gulpfile.js. See calls to copy common modules.

**Comment by crshnbrn66** [comment]
Ok I suspect that you are intending that utility.ps1 to copy to the same dir as each task? When this compiled and installed for me it didnt copy the file in.  When i put them with each task things are golden and work as expected.

**Comment by jabbera** [comment]
Yup. You ran gulp package and it didn't copy the files?

**Comment by jabbera** [comment]
I publish a compiled version on the marketplace if you don't want the pain of compiling yourself.

**Comment by crshnbrn66** [comment]
That maybe where i went sideways. I didn't run the Gulp package. Thank you for the clarification

**Comment by crshnbrn66** [comment]
Thank you
